[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Colman Humphrey <colmanhumphrey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# don't need to do it exactly this way, following convention
# happy to use package.name default here, so we don't specify
# a name field
path = "src/lib.rs"

[[bin]]
# double brackets because it's an array here -
# can have multiple binaries if we want
path = "src/main.rs"
name = "app"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.1.0"
serde = { version = "1", features = ["derive"] }
config = "0.10.1"

[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = [ "runtime-tokio", "macros", "postgres", "uuid", "chrono", "migrate" ]

[dev-dependencies]
reqwest = "0.10.8"
tokio = "0.2.22"
